default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vidur
  password: Vidur@1234
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: user_projects_development

test:
  <<: *default
  database: user_projects_test

production:
  primary: &primary_production
    <<: *default
    database: user_projects_production
    username: user_projects
    password: <%= ENV["USER_PROJECTS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: user_projects_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: user_projects_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: user_projects_production_cable
    migrations_paths: db/cable_migrate
